name: blue_ribbon
description: "reading for everyone"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  audioplayers: ^6.1.0
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_gemini: ^2.0.5
  google_fonts: ^6.2.0
  supabase_flutter: ^2.8.0
  lottie: ^3.1.3
  http: ^1.1.0
  file_picker: ^8.1.4
  read_pdf_text: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/Logo/
    - assets/
  uses-material-design: true
